# Validation-only policy seam in the pinned driver. Managed sources remain intact.
# Refuse an upstream change until the state-machine edit has been reviewed again.
function(jelli_panel_sleep_trial)
    idf_component_get_property(driver_lib espressif__esp_lcd_co5300 COMPONENT_LIB)
    idf_component_get_property(driver_dir espressif__esp_lcd_co5300 COMPONENT_DIR)
    set(original "${driver_dir}/esp_lcd_co5300_spi.c")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${original}")
    file(SHA256 "${original}" digest)
    if(NOT digest STREQUAL "823bda75000ebe4236ef06911cf26fc873e6507c8cc5de17a5104d89d19a9c34")
        message(FATAL_ERROR "CO5300 sleep trial requires reviewed 2.2.0 source; refusing patch")
    endif()
    file(READ "${original}" contents)
    set(before "        if (co5300->reset_gpio_num >= 0) {\n            const uint8_t dstb = CO5300_DSTBON_ENTER;")
    set(after "        if (co5300->reset_gpio_num >= 0 && jelli_panel_trial_deep_standby()) {\n            const uint8_t dstb = CO5300_DSTBON_ENTER;")
    string(FIND "${contents}" "${before}" position)
    if(position LESS 0)
        message(FATAL_ERROR "CO5300 sleep policy anchor missing")
    endif()
    string(REPLACE "${before}" "${after}" contents "${contents}")
    set(contents "#include <stdbool.h>\nextern bool jelli_panel_trial_deep_standby(void);\n${contents}")
    set(generated "${CMAKE_BINARY_DIR}/jelli-generated/co5300_sleep_trial.c")
    file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/jelli-generated")
    file(CONFIGURE OUTPUT "${generated}" CONTENT "${contents}" @ONLY)
    get_target_property(sources ${driver_lib} SOURCES)
    set(replaced)
    foreach(source IN LISTS sources)
        if(source MATCHES "(^|/)esp_lcd_co5300_spi[.]c$")
            list(APPEND replaced "${generated}")
        else()
            list(APPEND replaced "${source}")
        endif()
    endforeach()
    set_property(TARGET ${driver_lib} PROPERTY SOURCES "${replaced}")
endfunction()
