#ifndef JELLI_BEHAVIOR_H
#define JELLI_BEHAVIOR_H
#include "jelli/game.h"

/* Stimulus-driven creature behaviour (RFC-005). Code defines what a stimulus,
 * condition and request mean; content/behaviors.json, generated by
 * cmake/JelliBehaviors.cmake, decides which states a species enters and when. */

#define JELLI_BEHAVIOR_STATE_CAPACITY 16u
#define JELLI_BEHAVIOR_REPERTOIRE_CAPACITY 8u
#define JELLI_BEHAVIOR_REACTION_CAPACITY 64u
#define JELLI_BEHAVIOR_AFFINITY_CAPACITY 16u
#define JELLI_BEHAVIOR_ANY 255u
#define JELLI_BEHAVIOR_NONE 255u
#define JELLI_BEHAVIOR_TICKS 10u /* Behaviour is evaluated once per simulated second. */

typedef enum {
    JELLI_STIM_IDLE,
    JELLI_STIM_PRESENT_CAUGHT,  /* value: prize index */
    JELLI_STIM_PRESENT_GIVEN,   /* value: prize index, or ANY for a plain gift */
    JELLI_STIM_PRESENT_OFFERED, /* value: prize index */
    JELLI_STIM_LOCATION,        /* value: new location */
    JELLI_STIM_NIGHT,
    JELLI_STIM_MORNING,
    JELLI_STIM_ACTIVITY_STARTED,  /* value: JelliActivityCode */
    JELLI_STIM_ACTIVITY_FINISHED, /* value: JelliActivityCode */
    JELLI_STIM_NEED_LOW,          /* value: JelliNeed */
    JELLI_STIM_POTTY_URGE,
    JELLI_STIM_TOUCHED, /* value: touch reaction level */
    JELLI_STIM_WOKE,    /* value: wake mood */
    JELLI_STIM_COUNT
} JelliStimulusKind;

/* Activity identity for ACTIVITY_* stimuli: a moment, a health routine, or a care activity. */
enum {
    JELLI_ACTIVITY_CODE_MOMENT = 0,  /* + moment ID (content/activities.json) */
    JELLI_ACTIVITY_CODE_HEALTH = 32, /* + JelliHealthActivity */
    JELLI_ACTIVITY_CODE_CARE = 64    /* + JelliActivity */
};

typedef struct {
    uint32_t min_ticks, max_ticks, cooldown_ticks;
    int16_t needs[JELLI_NEED_COUNT];
    int16_t bond;
    uint16_t ends_on;        /* Bit per JelliStimulusKind that ends the state early. */
    uint8_t request_command; /* JelliCommandKind that answers the state, or NONE. */
    uint8_t request_value;   /* Required command value, or ANY. */
    uint16_t request_bond;   /* Bond gained when the request is answered. */
    uint8_t on_timeout;      /* JelliBehaviorTimeout when the state expires unanswered. */
    const char *name;
} JelliBehaviorState;

typedef enum { JELLI_WHEN_ALWAYS, JELLI_WHEN_YES, JELLI_WHEN_NO } JelliTriState;
typedef enum { JELLI_TIMEOUT_NOTHING, JELLI_TIMEOUT_ACCIDENT } JelliBehaviorTimeout;

/* JELLI_EVENT_STATUS codes; value is the state index. 0 and 1 are health/sleep and evolution. */
enum {
    JELLI_STATUS_BEHAVIOR_BEGAN = 2,
    JELLI_STATUS_BEHAVIOR_ENDED = 3,
    JELLI_STATUS_BEHAVIOR_ANSWERED = 4,
    JELLI_STATUS_ACCIDENT = 5
};

typedef struct {
    uint8_t on, value; /* JelliStimulusKind and its value, or ANY. */
    uint8_t state, weight, chance_pct;
    uint8_t location; /* Required location, or ANY. */
    uint8_t night;    /* JelliTriState. */
    uint8_t mood_min, mood_max;
    uint16_t bond_min;
} JelliBehaviorReaction;

typedef struct {
    uint8_t moment, bonus_pct;
} JelliAffinity;

typedef struct {
    uint8_t first_reaction, reaction_count, first_affinity, affinity_count;
} JelliRepertoire;

typedef struct {
    uint16_t night_start_minute, night_end_minute, need_low;
} JelliBehaviorRules;

/* How a species responds to touch (content/behaviors.json "touch", per repertoire override). */
typedef struct {
    uint16_t load_per_tap, upset_load, overload_load, decay_per_tick, reaction_ticks;
    uint16_t happy_gain, upset_loss, bond_gain;
} JelliTouchRules;
/* Index 0 is the default; repertoire r uses r + 1. */
extern const JelliTouchRules jelli_behavior_touch[];
extern const unsigned jelli_behavior_touch_ticks_max;
const JelliTouchRules *jelli_behavior_touch_rules(const JelliPet *pet);

extern const JelliBehaviorRules jelli_behavior_rules;
extern const JelliBehaviorState jelli_behavior_states[];
extern const unsigned jelli_behavior_state_count;
extern const JelliBehaviorReaction jelli_behavior_reactions[];
extern const JelliAffinity jelli_behavior_affinities[];
extern const JelliRepertoire jelli_behavior_repertoires[];
extern const unsigned jelli_behavior_repertoire_count;
extern const uint8_t jelli_behavior_form_repertoire[]; /* Per catalog form, or NONE. */

/* Queue a stimulus for the active pet; it is matched at the next behaviour second. */
void jelli_behavior_stimulus(JelliGame *game, unsigned kind, unsigned value);
/* Run once per advanced tick for the active pet, after other endpoint work. */
void jelli_behavior_step(JelliGame *game, JelliPet *pet, uint64_t old_ticks, bool offline);
/* After a successful command: answer a matching request and raise activity stimuli. */
void jelli_behavior_command(JelliGame *game, JelliCommand command, unsigned before_location,
                            unsigned before_activity);
/* Percent applied to a moment's gains for this pet's species (100 = unchanged). */
unsigned jelli_behavior_moment_percent(const JelliPet *pet, unsigned moment);
const JelliBehaviorState *jelli_behavior_current(const JelliPet *pet);
#endif
