# Stable saved location IDs. New places also need renderer/travel support.
function(jelli_location_names root output)
  set(source "${root}/content/locations.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" locations)
  if(NOT version EQUAL 1 OR NOT count EQUAL 2)
    message(FATAL_ERROR "Location catalog needs version 1 and the two supported places")
  endif()
  set(names "")
  set(supported home garden)
  foreach(i RANGE 0 1)
    string(JSON id GET "${data}" locations ${i} id)
    string(JSON key GET "${data}" locations ${i} key)
    string(JSON name GET "${data}" locations ${i} name)
    list(GET supported ${i} expected)
    if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT key STREQUAL expected OR
       NOT name MATCHES "^[A-Z0-9 ]+$")
      message(FATAL_ERROR "Location ${i} must retain its supported stable ID/key ${expected}")
    endif()
    list(APPEND names "${key}")
  endforeach()
  set(${output} "${names}" PARENT_SCOPE)
endfunction()
