# Natural potty cycle from content/potty.json; see RFC-005.
function(jelli_potty_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/potty.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON fields LENGTH "${data}")
  string(JSON version GET "${data}" version)
  if(NOT fields EQUAL 8 OR NOT version EQUAL 1)
    message(FATAL_ERROR "Potty rules need version 1 and exactly seven rule fields")
  endif()
  set(values "")
  foreach(field per_meal per_drink drain_per_minute urge_threshold minimum_to_go hygiene_gain bond_gain)
    string(JSON ${field} GET "${data}" ${field})
    if(NOT ${field} MATCHES "^[0-9]+$" OR ${field} GREATER 1000)
      message(FATAL_ERROR "Potty ${field} must be 0..1000")
    endif()
    string(APPEND values "${${field}}u, ")
  endforeach()
  if(drain_per_minute LESS 1 OR urge_threshold LESS 1 OR minimum_to_go GREATER urge_threshold)
    message(FATAL_ERROR "Potty urge must drain, have a threshold, and allow a break before it")
  endif()
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_potty_data.c")
  file(WRITE "${path}" "#include \"jelli/potty.h\"\nconst JelliPottyRules jelli_potty_rules = {${values}};\n")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
