function(jelli_food_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/food.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" foods)
  if(NOT version EQUAL 1 OR count LESS 1 OR count GREATER 8)
    message(FATAL_ERROR "Invalid food catalog")
  endif()
  set(body "#include \"jelli/nutrition.h\"\nconst unsigned jelli_food_count = ${count}u;\nconst JelliFood jelli_foods[9] = {\n")
  math(EXPR last "${count} - 1")
  foreach(i RANGE 0 ${last})
    foreach(field id name fullness hydration icon)
      string(JSON ${field} GET "${data}" foods ${i} ${field})
    endforeach()
    string(LENGTH "${name}" length)
    if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT name MATCHES "^[A-Z0-9 ]+$" OR length GREATER 10 OR NOT fullness MATCHES "^[0-9]+$" OR fullness GREATER 1000 OR NOT hydration MATCHES "^[0-9]+$" OR hydration GREATER 1000 OR NOT icon MATCHES "^[0-9]+$" OR icon LESS 6001 OR icon GREATER 6015)
      message(FATAL_ERROR "Invalid food ${i}")
    endif()
    string(APPEND body "    {\"${name}\", ${fullness}u, ${hydration}u, ${icon}u},\n")
  endforeach()
  string(APPEND body "};\n")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_food_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
