function(jelli_activity_pet_costs data valid_forms out)
  string(JSON count LENGTH "${data}" pet_costs)
  list(LENGTH valid_forms form_count)
  if(NOT count EQUAL form_count)
    message(FATAL_ERROR "Every pet form needs one activity cost profile")
  endif()
  math(EXPR last "${count} - 1")
  set(seen "")
  set(rows "")
  foreach(i RANGE 0 ${last})
    string(JSON form GET "${data}" pet_costs ${i} form)
    if(NOT form IN_LIST valid_forms OR form IN_LIST seen)
      message(FATAL_ERROR "Activity cost profiles need unique known forms")
    endif()
    list(APPEND seen "${form}")
    foreach(meter energy hydration)
      string(JSON ${meter} GET "${data}" pet_costs ${i} ${meter}_pct)
      if(NOT ${meter} MATCHES "^[0-9]+$" OR ${meter} GREATER 300)
        message(FATAL_ERROR "Pet ${meter} cost multiplier must be 0..300 percent")
      endif()
    endforeach()
    string(APPEND rows "    {${form}u, ${energy}u, ${hydration}u},\n")
  endforeach()
  set(${out} "const JelliActivityPetCosts jelli_activity_pet_costs[] = {\n${rows}};\nconst unsigned jelli_activity_pet_cost_count = ${count}u;\n" PARENT_SCOPE)
endfunction()

function(jelli_activity_assets root out)
  set(source "${root}/assets/slice/assets.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON count LENGTH "${data}" assets)
  math(EXPR last "${count} - 1")
  set(ids "")
  foreach(i RANGE 0 ${last})
    string(JSON id GET "${data}" assets ${i} id)
    if(NOT id MATCHES "^[0-9]+$" OR id IN_LIST ids)
      message(FATAL_ERROR "Asset IDs must be unique nonnegative integers")
    endif()
    list(APPEND ids "${id}")
  endforeach()
  set(${out} "${ids}" PARENT_SCOPE)
endfunction()
