# Stimulus-driven creature behaviour from content/behaviors.json (RFC-005).
# Names resolve to C enum constants so generated tables never carry bare numbers.
set(JELLI_BEHAVIOR_STIMULI idle present_caught present_given present_offered location night morning
    activity_started activity_finished need_low potty_urge touched woke)
set(JELLI_BEHAVIOR_NEEDS satiety energy hygiene amusement social)
set(JELLI_BEHAVIOR_COMMANDS feed play clean care rest wake gift claim activate travel bedtime moment
    health touch water exercise)
set(JELLI_BEHAVIOR_HEALTH brush medicine shot wash stretch floss mouthwash spit cleanup potty)
set(JELLI_BEHAVIOR_CARE eating playing cleaning caring giving exercising)
set(JELLI_BEHAVIOR_LOCATIONS home garden)

# Optional JSON member: sets out to the value, or to fallback when absent.
function(jelli_behavior_opt out fallback data)
  string(JSON value ERROR_VARIABLE missing GET "${data}" ${ARGN})
  if(missing)
    set(value "${fallback}")
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(jelli_behavior_index out list name label)
  list(FIND ${list} "${name}" index)
  if(index LESS 0)
    message(FATAL_ERROR "Unknown ${label} '${name}'; expected one of: ${${list}}")
  endif()
  set(${out} ${index} PARENT_SCOPE)
endfunction()

function(jelli_behavior_bounded value low high label)
  if(NOT value MATCHES "^-?[0-9]+$" OR value LESS low OR value GREATER high)
    message(FATAL_ERROR "${label} must be ${low}..${high}, got '${value}'")
  endif()
endfunction()

function(jelli_behavior_state data i states_list out)
  string(JSON name GET "${data}" states ${i} name)
  string(JSON low GET "${data}" states ${i} duration_s 0)
  string(JSON high GET "${data}" states ${i} duration_s 1)
  string(JSON cooldown GET "${data}" states ${i} cooldown_s)
  jelli_behavior_bounded("${low}" 1 3600 "State ${name} minimum duration (s)")
  jelli_behavior_bounded("${high}" ${low} 3600 "State ${name} maximum duration (s)")
  jelli_behavior_bounded("${cooldown}" 0 36000 "State ${name} cooldown (s)")
  set(needs "")
  foreach(need IN LISTS JELLI_BEHAVIOR_NEEDS)
    jelli_behavior_opt(delta 0 "${data}" states ${i} effects ${need})
    jelli_behavior_bounded("${delta}" -100 100 "State ${name} ${need} effect")
    string(APPEND needs "${delta}, ")
  endforeach()
  jelli_behavior_opt(bond 0 "${data}" states ${i} effects bond)
  jelli_behavior_bounded("${bond}" -100 100 "State ${name} bond effect")
  set(mask "0u")
  string(JSON ends LENGTH "${data}" states ${i} ends_on)
  if(ends GREATER 0)
    math(EXPR last "${ends} - 1")
    foreach(j RANGE 0 ${last})
      string(JSON stimulus GET "${data}" states ${i} ends_on ${j})
      jelli_behavior_index(unused JELLI_BEHAVIOR_STIMULI "${stimulus}" "stimulus in ${name}.ends_on")
      string(TOUPPER "${stimulus}" stimulus)
      string(APPEND mask " | (1u << JELLI_STIM_${stimulus})")
    endforeach()
  endif()
  jelli_behavior_opt(command "" "${data}" states ${i} request command)
  set(request "JELLI_BEHAVIOR_NONE, JELLI_BEHAVIOR_ANY, 0u")
  if(NOT command STREQUAL "")
    jelli_behavior_index(unused JELLI_BEHAVIOR_COMMANDS "${command}" "request command in ${name}")
    string(TOUPPER "${command}" upper)
    jelli_behavior_opt(health "" "${data}" states ${i} request health)
    set(value "JELLI_BEHAVIOR_ANY")
    if(NOT health STREQUAL "")
      jelli_behavior_index(unused JELLI_BEHAVIOR_HEALTH "${health}" "request health in ${name}")
      string(TOUPPER "${health}" health)
      set(value "JELLI_HEALTH_${health}")
    endif()
    jelli_behavior_opt(reward 0 "${data}" states ${i} request bond)
    jelli_behavior_bounded("${reward}" 0 100 "State ${name} request bond")
    set(request "JELLI_CMD_${upper}, ${value}, ${reward}u")
  endif()
  math(EXPR low "${low} * 10")
  math(EXPR high "${high} * 10")
  math(EXPR cooldown "${cooldown} * 10")
  set(${out} "    {${low}u, ${high}u, ${cooldown}u, {${needs}}, ${bond}, ${mask}, ${request}, \"${name}\"},\n" PARENT_SCOPE)
endfunction()

# Reaction value: the member that matches its stimulus kind, or ANY.
function(jelli_behavior_value data r i on moments out)
  set(value "JELLI_BEHAVIOR_ANY")
  if(on STREQUAL "need_low")
    jelli_behavior_opt(need "" "${data}" repertoires ${r} reactions ${i} need)
    if(NOT need STREQUAL "")
      jelli_behavior_index(unused JELLI_BEHAVIOR_NEEDS "${need}" "reaction need")
      string(TOUPPER "${need}" need)
      set(value "JELLI_${need}")
    endif()
  elseif(on STREQUAL "location")
    jelli_behavior_opt(place "" "${data}" repertoires ${r} reactions ${i} location)
    if(NOT place STREQUAL "")
      jelli_behavior_index(index JELLI_BEHAVIOR_LOCATIONS "${place}" "reaction location")
      set(value "${index}u")
    endif()
  elseif(on MATCHES "^activity_")
    jelli_behavior_opt(moment "" "${data}" repertoires ${r} reactions ${i} moment)
    jelli_behavior_opt(health "" "${data}" repertoires ${r} reactions ${i} health)
    jelli_behavior_opt(care "" "${data}" repertoires ${r} reactions ${i} activity)
    if(NOT moment STREQUAL "")
      jelli_behavior_index(index ${moments} "${moment}" "reaction moment")
      set(value "JELLI_ACTIVITY_CODE_MOMENT + ${index}u")
    elseif(NOT health STREQUAL "")
      jelli_behavior_index(unused JELLI_BEHAVIOR_HEALTH "${health}" "reaction health")
      string(TOUPPER "${health}" health)
      set(value "JELLI_ACTIVITY_CODE_HEALTH + JELLI_HEALTH_${health}")
    elseif(NOT care STREQUAL "")
      jelli_behavior_index(unused JELLI_BEHAVIOR_CARE "${care}" "reaction activity")
      string(TOUPPER "${care}" care)
      set(value "JELLI_ACTIVITY_CODE_CARE + JELLI_${care}")
    endif()
  elseif(on MATCHES "^present_")
    jelli_behavior_opt(prize "" "${data}" repertoires ${r} reactions ${i} prize)
    if(NOT prize STREQUAL "")
      jelli_behavior_bounded("${prize}" 0 8 "reaction prize index")
      set(value "${prize}u")
    endif()
  endif()
  set(${out} "${value}" PARENT_SCOPE)
endfunction()

function(jelli_behavior_reaction data r i states moments out)
  string(JSON on GET "${data}" repertoires ${r} reactions ${i} on)
  string(JSON state GET "${data}" repertoires ${r} reactions ${i} state)
  jelli_behavior_index(unused JELLI_BEHAVIOR_STIMULI "${on}" "reaction stimulus")
  string(TOUPPER "${on}" upper)
  jelli_behavior_index(state_index ${states} "${state}" "reaction state")
  jelli_behavior_value("${data}" ${r} ${i} "${on}" ${moments} value)
  jelli_behavior_opt(weight 1 "${data}" repertoires ${r} reactions ${i} weight)
  jelli_behavior_opt(chance 100 "${data}" repertoires ${r} reactions ${i} chance_pct)
  jelli_behavior_bounded("${weight}" 1 100 "Reaction ${on}->${state} weight")
  jelli_behavior_bounded("${chance}" 1 100 "Reaction ${on}->${state} chance_pct")
  jelli_behavior_opt(place "" "${data}" repertoires ${r} reactions ${i} when location)
  set(location "JELLI_BEHAVIOR_ANY")
  if(NOT place STREQUAL "")
    jelli_behavior_index(index JELLI_BEHAVIOR_LOCATIONS "${place}" "condition location")
    set(location "${index}u")
  endif()
  jelli_behavior_opt(night "" "${data}" repertoires ${r} reactions ${i} when night)
  if(night STREQUAL "")
    set(night "JELLI_WHEN_ALWAYS")
  elseif(night)
    set(night "JELLI_WHEN_YES")
  else()
    set(night "JELLI_WHEN_NO")
  endif()
  jelli_behavior_opt(mood_min 0 "${data}" repertoires ${r} reactions ${i} when mood_min)
  jelli_behavior_opt(mood_max 100 "${data}" repertoires ${r} reactions ${i} when mood_max)
  jelli_behavior_opt(bond_min 0 "${data}" repertoires ${r} reactions ${i} when bond_min)
  jelli_behavior_bounded("${mood_min}" 0 100 "Condition mood_min")
  jelli_behavior_bounded("${mood_max}" ${mood_min} 100 "Condition mood_max")
  jelli_behavior_bounded("${bond_min}" 0 1000 "Condition bond_min")
  set(${out} "    {JELLI_STIM_${upper}, ${value}, ${state_index}u, ${weight}u, ${chance}u, ${location}, ${night}, ${mood_min}u, ${mood_max}u, ${bond_min}u},\n" PARENT_SCOPE)
endfunction()

function(jelli_behavior_names data member out)
  set(names "")
  string(JSON count LENGTH "${data}" ${member})
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(i RANGE 0 ${last})
      string(JSON name GET "${data}" ${member} ${i} name)
      list(APPEND names "${name}")
    endforeach()
  endif()
  set(${out} "${names}" PARENT_SCOPE)
endfunction()

function(jelli_behavior_repertoires data states moments forms out)
  string(JSON count LENGTH "${data}" repertoires)
  list(LENGTH ${forms} form_count)
  set(owner "")
  foreach(f RANGE 1 ${form_count})
    list(APPEND owner "JELLI_BEHAVIOR_NONE")
  endforeach()
  set(reactions "")
  set(affinities "")
  set(table "")
  set(reaction_total 0)
  set(affinity_total 0)
  if(count GREATER 8)
    message(FATAL_ERROR "At most 8 repertoires")
  endif()
  math(EXPR last "${count} - 1")
  foreach(r RANGE 0 ${last})
    if(count EQUAL 0)
      break()
    endif()
    string(JSON name GET "${data}" repertoires ${r} name)
    string(JSON owned LENGTH "${data}" repertoires ${r} forms)
    math(EXPR last_form "${owned} - 1")
    foreach(j RANGE 0 ${last_form})
      string(JSON form GET "${data}" repertoires ${r} forms ${j})
      jelli_behavior_index(index ${forms} "${form}" "form in repertoire ${name}")
      list(GET owner ${index} previous)
      if(NOT previous STREQUAL "JELLI_BEHAVIOR_NONE")
        message(FATAL_ERROR "Form ${form} is in two repertoires")
      endif()
      list(REMOVE_AT owner ${index})
      list(INSERT owner ${index} "${r}u")
    endforeach()
    string(JSON reaction_count LENGTH "${data}" repertoires ${r} reactions)
    math(EXPR last_reaction "${reaction_count} - 1")
    foreach(i RANGE 0 ${last_reaction})
      jelli_behavior_reaction("${data}" ${r} ${i} ${states} ${moments} row)
      string(APPEND reactions "${row}")
    endforeach()
    jelli_behavior_opt(affinity_text "[]" "${data}" repertoires ${r} affinities)
    string(JSON affinity_count LENGTH "${affinity_text}")
    if(affinity_count GREATER 0)
      math(EXPR last_affinity "${affinity_count} - 1")
      foreach(i RANGE 0 ${last_affinity})
        string(JSON moment GET "${affinity_text}" ${i} moment)
        string(JSON bonus GET "${affinity_text}" ${i} bonus_pct)
        jelli_behavior_index(index ${moments} "${moment}" "affinity moment")
        jelli_behavior_bounded("${bonus}" 0 200 "Affinity ${moment} bonus_pct")
        string(APPEND affinities "    {${index}u, ${bonus}u},\n")
      endforeach()
    endif()
    string(APPEND table "    {${reaction_total}u, ${reaction_count}u, ${affinity_total}u, ${affinity_count}u}, /* ${name} */\n")
    math(EXPR reaction_total "${reaction_total} + ${reaction_count}")
    math(EXPR affinity_total "${affinity_total} + ${affinity_count}")
  endforeach()
  if(reaction_total GREATER 64 OR affinity_total GREATER 16)
    message(FATAL_ERROR "At most 64 reactions and 16 affinities in total")
  endif()
  if(reactions STREQUAL "")
    set(reactions "    {0},\n") # C needs a non-empty array; counts keep it unused.
  endif()
  if(affinities STREQUAL "")
    set(affinities "    {0},\n")
  endif()
  if(table STREQUAL "")
    set(table "    {0},\n")
  endif()
  list(JOIN owner ", " owner)
  set(${out} "const JelliBehaviorReaction jelli_behavior_reactions[] = {\n${reactions}};\nconst JelliAffinity jelli_behavior_affinities[] = {\n${affinities}};\nconst JelliRepertoire jelli_behavior_repertoires[] = {\n${table}};\nconst unsigned jelli_behavior_repertoire_count = ${count}u;\nconst uint8_t jelli_behavior_form_repertoire[] = {${owner}};\n" PARENT_SCOPE)
endfunction()

function(jelli_behaviors_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  foreach(file behaviors activities pets)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${root}/content/${file}.json")
    file(READ "${root}/content/${file}.json" ${file})
  endforeach()
  string(JSON version GET "${behaviors}" version)
  string(JSON start GET "${behaviors}" night start_minute)
  string(JSON end GET "${behaviors}" night end_minute)
  string(JSON need_low GET "${behaviors}" need_low)
  jelli_behavior_bounded("${version}" 1 1 "Behaviour version")
  jelli_behavior_bounded("${start}" 0 1439 "night.start_minute")
  jelli_behavior_bounded("${end}" 0 1439 "night.end_minute")
  jelli_behavior_bounded("${need_low}" 1 999 "need_low")
  jelli_behavior_names("${behaviors}" states state_names)
  jelli_behavior_names("${activities}" moments moment_names)
  jelli_behavior_names("${pets}" forms form_names)
  list(LENGTH state_names state_count)
  if(state_count GREATER 16)
    message(FATAL_ERROR "At most 16 behaviour states")
  endif()
  set(body "#include \"jelli/behavior.h\"\nconst JelliBehaviorRules jelli_behavior_rules = {${start}u, ${end}u, ${need_low}u};\nconst JelliBehaviorState jelli_behavior_states[] = {\n")
  if(state_count EQUAL 0)
    string(APPEND body "    {0},\n")
  else()
    math(EXPR last "${state_count} - 1")
    foreach(i RANGE 0 ${last})
      list(GET state_names ${i} name)
      list(FIND state_names "${name}" first)
      if(NOT first EQUAL i OR NOT name MATCHES "^[a-z][a-z0-9_]*$")
        message(FATAL_ERROR "State names must be unique lower_snake_case: ${name}")
      endif()
      jelli_behavior_state("${behaviors}" ${i} state_names row)
      string(APPEND body "${row}")
    endforeach()
  endif()
  string(APPEND body "};\nconst unsigned jelli_behavior_state_count = ${state_count}u;\n")
  jelli_behavior_repertoires("${behaviors}" state_names moment_names form_names tables)
  string(APPEND body "${tables}")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_behaviors_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
