# Natural potty cycle from content/potty.json; see RFC-005.
# A 1..4 entry list of asset IDs, emitted as C initialiser values and a count.
function(jelli_potty_sprites data list values_variable count_variable)
  string(JSON count LENGTH "${data}" ${list})
  if(count LESS 1 OR count GREATER 4)
    message(FATAL_ERROR "Potty ${list} needs 1..4 sprite asset IDs")
  endif()
  set(values "")
  math(EXPR last "${count} - 1")
  foreach(i RANGE 0 ${last})
    string(JSON sprite GET "${data}" ${list} ${i})
    if(NOT sprite MATCHES "^[0-9]+$" OR sprite LESS 1)
      message(FATAL_ERROR "Potty ${list} entries are asset IDs")
    endif()
    string(APPEND values "${sprite}u, ")
  endforeach()
  set(${values_variable} "${values}" PARENT_SCOPE)
  set(${count_variable} ${count} PARENT_SCOPE)
endfunction()

function(jelli_potty_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/potty.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON fields LENGTH "${data}")
  string(JSON version GET "${data}" version)
  if(NOT fields EQUAL 15 OR NOT version EQUAL 1)
    message(FATAL_ERROR "Potty rules need version 1 and exactly fourteen rule fields")
  endif()
  set(values "")
  foreach(field per_meal per_drink drain_per_minute urge_threshold minimum_to_go hygiene_gain bond_gain
          accident_hygiene mess_hygiene_per_minute mess_frame_ms mess_mood_penalty)
    string(JSON ${field} GET "${data}" ${field})
    if(NOT ${field} MATCHES "^[0-9]+$" OR ${field} GREATER 1000)
      message(FATAL_ERROR "Potty ${field} must be 0..1000")
    endif()
    string(APPEND values "${${field}}u, ")
  endforeach()
  if(mess_frame_ms LESS 1)
    message(FATAL_ERROR "Potty mess needs a positive frame time")
  endif()
  foreach(list mess_sprites broom_sprites)
    jelli_potty_sprites("${data}" ${list} sprites sprite_count)
    string(APPEND values "{${sprites}}, ${sprite_count}u, ")
  endforeach()
  string(JSON sweep_steps GET "${data}" sweep_steps)
  if(NOT sweep_steps MATCHES "^[0-9]+$" OR sweep_steps LESS 2 OR sweep_steps GREATER 32)
    message(FATAL_ERROR "Potty sweep_steps must be 2..32")
  endif()
  string(APPEND values "${sweep_steps}u")
  if(drain_per_minute LESS 1 OR urge_threshold LESS 1 OR minimum_to_go GREATER urge_threshold)
    message(FATAL_ERROR "Potty urge must drain, have a threshold, and allow a break before it")
  endif()
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_potty_data.c")
  file(WRITE "${path}" "#include \"jelli/potty.h\"\nconst JelliPottyRules jelli_potty_rules = {${values}};\n")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
