function(jelli_collection_check_name value label)
  string(LENGTH "${value}" length)
  if(NOT value MATCHES "^[A-Z0-9 ]+$" OR length GREATER 16)
    message(FATAL_ERROR "Invalid ${label} name")
  endif()
endfunction()

# Forms: stable IDs 0..7 (one bit each in the saved reached-forms mask).
function(jelli_collection_forms data body_variable count_variable)
  string(JSON count LENGTH "${data}" forms)
  if(count LESS 1 OR count GREATER 8)
    message(FATAL_ERROR "A catalog needs 1..8 forms")
  endif()
  math(EXPR last "${count} - 1")
  set(body "const JelliCollectionForm jelli_collection_forms[] = {\n")
  foreach(i RANGE 0 ${last})
    foreach(field id name portrait art)
      string(JSON ${field} GET "${data}" forms ${i} ${field})
    endforeach()
    if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT portrait MATCHES "^[0-9]+$" OR portrait LESS 1 OR NOT art MATCHES "^[a-z][a-z0-9-]*$")
      message(FATAL_ERROR "Unsupported form profile ${i}")
    endif()
    jelli_collection_check_name("${name}" "form ${i}")
    string(APPEND body "    {${portrait}u, \"${name}\"},\n")
  endforeach()
  string(APPEND body "};\nconst unsigned jelli_collection_form_count = ${count}u;\n")
  set(${body_variable} "${body}" PARENT_SCOPE)
  set(${count_variable} ${count} PARENT_SCOPE)
endfunction()

# Evolution sets: IDs 1..4 in order, one or two forms, each form in one set.
# Two-form sets grow after growth_ticks; single-form sets must declare zero.
function(jelli_collection_sets data form_count body_variable count_variable)
  string(JSON count LENGTH "${data}" evolution_sets)
  if(count LESS 1 OR count GREATER 4)
    message(FATAL_ERROR "A catalog needs 1..4 evolution sets")
  endif()
  math(EXPR last "${count} - 1")
  set(used "")
  set(body "const JelliEvolutionSet jelli_evolution_sets[] = {\n")
  foreach(i RANGE 0 ${last})
    string(JSON id GET "${data}" evolution_sets ${i} id)
    string(JSON growth GET "${data}" evolution_sets ${i} growth_ticks)
    string(JSON forms LENGTH "${data}" evolution_sets ${i} forms)
    math(EXPR expected "${i} + 1")
    if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL expected OR forms LESS 1 OR forms GREATER 2 OR NOT growth MATCHES "^[0-9]+$")
      message(FATAL_ERROR "Invalid evolution set ${i}")
    endif()
    if((forms EQUAL 2 AND (growth LESS 1 OR growth GREATER 864000)) OR (forms EQUAL 1 AND NOT growth EQUAL 0))
      message(FATAL_ERROR "Invalid growth for evolution set ${id}")
    endif()
    set(members "")
    math(EXPR last_form "${forms} - 1")
    foreach(j RANGE 0 ${last_form})
      string(JSON form GET "${data}" evolution_sets ${i} forms ${j})
      if(NOT form MATCHES "^[0-9]+$" OR NOT form LESS form_count OR form IN_LIST used)
        message(FATAL_ERROR "Evolution set ${id} references an invalid or shared form")
      endif()
      list(APPEND used ${form})
      string(APPEND members "${form}u, ")
    endforeach()
    string(APPEND body "    {${forms}u, {${members}}, ${growth}u},\n")
  endforeach()
  string(APPEND body "};\nconst unsigned jelli_evolution_set_count = ${count}u;\n")
  set(${body_variable} "${body}" PARENT_SCOPE)
  set(${count_variable} ${count} PARENT_SCOPE)
endfunction()

function(jelli_collection_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/pets.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON root_fields LENGTH "${data}")
  if(NOT root_fields EQUAL 4)
    message(FATAL_ERROR "Unknown or missing catalog fields")
  endif()
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" entries)
  if(NOT version EQUAL 2 OR NOT count EQUAL 9)
    message(FATAL_ERROR "Invalid bounded pet catalog")
  endif()
  jelli_collection_forms("${data}" forms_body form_count)
  jelli_collection_sets("${data}" ${form_count} sets_body set_count)
  set(body "#include \"jelli/collection.h\"\nconst JelliCollectionEntry jelli_collection_entries[9] = {\n")
  foreach(i RANGE 0 8)
    foreach(field id name unlock_prize hint evolution_set)
      string(JSON ${field} GET "${data}" entries ${i} ${field})
    endforeach()
    math(EXPR expected "${i} + 1")
    string(LENGTH "${hint}" hint_length)
    if(NOT id MATCHES "^[0-9]+$" OR NOT evolution_set MATCHES "^[0-9]+$" OR evolution_set LESS 1 OR evolution_set GREATER set_count OR NOT id EQUAL expected OR NOT unlock_prize MATCHES "^[0-9]+$" OR unlock_prize GREATER 9 OR NOT hint MATCHES "^[A-Z0-9 ]+$" OR hint_length GREATER 24)
      message(FATAL_ERROR "Invalid pet entry ${i}")
    endif()
    jelli_collection_check_name("${name}" "pet entry ${i}")
    if(i EQUAL 0 AND NOT unlock_prize EQUAL 0)
      message(FATAL_ERROR "The Jelli family must remain a starter")
    endif()
    string(APPEND body "    {${id}u, ${unlock_prize}u, ${evolution_set}u, \"${name}\", \"${hint}\"},\n")
  endforeach()
  string(APPEND body "};\n${forms_body}${sets_body}")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_collection_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
