# Moments (the Activities ring) from content/activities.json; see RFC-005.
function(jelli_activities_moment data i body_variable)
  foreach(field id name kind suggest_hour location icon prop)
    string(JSON ${field} GET "${data}" moments ${i} ${field})
  endforeach()
  string(LENGTH "${name}" name_length)
  if(NOT id EQUAL i OR NOT name MATCHES "^[A-Z0-9 ]+$" OR name_length GREATER 12)
    message(FATAL_ERROR "Invalid moment ${i}: id must equal its position; name is A-Z/0-9, at most 12")
  endif()
  if(NOT kind MATCHES "^(feed|play)$" OR NOT location MATCHES "^(stay|home|garden)$")
    message(FATAL_ERROR "Invalid moment ${name}: kind feed|play, location stay|home|garden")
  endif()
  if(NOT suggest_hour MATCHES "^-?[0-9]+$" OR suggest_hour LESS -1 OR suggest_hour GREATER 23)
    message(FATAL_ERROR "Invalid moment ${name}: suggest_hour is -1 (never) or 0..23")
  endif()
  if(NOT icon MATCHES "^[0-9]+$" OR icon LESS 1 OR NOT prop MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Invalid moment ${name}: icon is an asset ID; prop is an asset ID or 0")
  endif()
  set(gains "")
  foreach(need satiety energy hygiene amusement social)
    string(JSON gain ERROR_VARIABLE missing GET "${data}" moments ${i} gains ${need})
    if(missing)
      set(gain 0)
    elseif(NOT gain MATCHES "^[0-9]+$" OR gain GREATER 1000)
      message(FATAL_ERROR "Invalid moment ${name}: ${need} gain is 0..1000")
    endif()
    string(APPEND gains "${gain}u, ")
  endforeach()
  string(JSON gain_count LENGTH "${data}" moments ${i} gains)
  string(JSON gain_text GET "${data}" moments ${i} gains)
  string(REGEX MATCHALL "\"[a-z_]+\"" gain_keys "${gain_text}")
  foreach(key IN LISTS gain_keys)
    if(NOT key MATCHES "^\"(satiety|energy|hygiene|amusement|social)\"$")
      message(FATAL_ERROR "Invalid moment ${name}: unknown need ${key}")
    endif()
  endforeach()
  string(TOUPPER "${kind}" kind)
  string(TOUPPER "${location}" location)
  if(suggest_hour EQUAL -1)
    set(suggest_hour 255)
  endif()
  set(${body_variable} "    {\"${name}\", JELLI_MOMENT_${kind}, JELLI_MOMENT_${location}, ${suggest_hour}u, {${gains}}, ${icon}u, ${prop}u},\n" PARENT_SCOPE)
endfunction()

# Favourite moments: profile = pet ID modulo profile count; each profile names its favourite
# moment per time-of-day window and when its bonus is strongest.
function(jelli_activities_favorites data moment_count out)
  string(JSON bond GET "${data}" favorites bond)
  string(JSON count LENGTH "${data}" favorites profiles)
  if(NOT bond MATCHES "^[0-9]+$" OR bond GREATER 100 OR count LESS 1 OR count GREATER 4)
    message(FATAL_ERROR "favorites needs bond 0..100 and 1..4 profiles")
  endif()
  set(rows "")
  math(EXPR last "${count} - 1")
  foreach(p RANGE 0 ${last})
    string(JSON name GET "${data}" favorites profiles ${p} name)
    string(JSON windows LENGTH "${data}" favorites profiles ${p} windows)
    if(windows LESS 1 OR windows GREATER 4)
      message(FATAL_ERROR "Favourite profile ${name} needs 1..4 windows")
    endif()
    set(cells "")
    set(previous 0)
    math(EXPR last_window "${windows} - 1")
    foreach(w RANGE 0 ${last_window})
      string(JSON until GET "${data}" favorites profiles ${p} windows ${w} until_minute)
      string(JSON moment GET "${data}" favorites profiles ${p} windows ${w} moment)
      if(NOT until MATCHES "^[0-9]+$" OR NOT until GREATER previous OR until GREATER 1440)
        message(FATAL_ERROR "Favourite profile ${name}: until_minute must rise, at most 1440")
      endif()
      set(index -1)
      math(EXPR last_moment "${moment_count} - 1")
      foreach(m RANGE 0 ${last_moment})
        string(JSON candidate GET "${data}" moments ${m} name)
        if(candidate STREQUAL moment)
          set(index ${m})
        endif()
      endforeach()
      if(index LESS 0)
        message(FATAL_ERROR "Favourite profile ${name}: unknown moment '${moment}'")
      endif()
      string(APPEND cells "{${until}u, ${index}u}, ")
      set(previous ${until})
    endforeach()
    if(NOT previous EQUAL 1440)
      message(FATAL_ERROR "Favourite profile ${name}: the last window must end at minute 1440")
    endif()
    foreach(field strong_from_minute strong_until_minute strong_bonus bonus)
      string(JSON ${field} GET "${data}" favorites profiles ${p} ${field})
      if(NOT ${field} MATCHES "^[0-9]+$" OR ${field} GREATER 1440)
        message(FATAL_ERROR "Favourite profile ${name}: ${field} out of range")
      endif()
    endforeach()
    if(strong_until_minute LESS strong_from_minute OR strong_bonus GREATER 200 OR bonus GREATER 200)
      message(FATAL_ERROR "Favourite profile ${name}: strong window or bonuses out of range")
    endif()
    string(APPEND rows "    {{${cells}}, ${windows}u, ${strong_from_minute}u, ${strong_until_minute}u, ${strong_bonus}u, ${bonus}u}, /* ${name} */\n")
  endforeach()
  set(${out} "const JelliFavoriteProfile jelli_favorite_profiles[] = {\n${rows}};\nconst unsigned jelli_favorite_profile_count = ${count}u;\nconst uint16_t jelli_favorite_bond = ${bond}u;\n" PARENT_SCOPE)
endfunction()

function(jelli_activities_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/activities.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" moments)
  if(NOT version EQUAL 1 OR count LESS 1 OR count GREATER 8)
    message(FATAL_ERROR "Activities need version 1 and 1..8 moments")
  endif()
  math(EXPR last "${count} - 1")
  set(body "#include \"jelli/activities.h\"\nconst JelliMoment jelli_moments[] = {\n")
  set(suggested 0)
  foreach(i RANGE 0 ${last})
    jelli_activities_moment("${data}" ${i} row)
    string(APPEND body "${row}")
    string(JSON hour GET "${data}" moments ${i} suggest_hour)
    if(NOT hour EQUAL -1)
      math(EXPR suggested "${suggested} + 1")
    endif()
  endforeach()
  if(suggested EQUAL 0)
    message(FATAL_ERROR "At least one moment must have a suggest_hour")
  endif()
  string(APPEND body "};\nconst unsigned jelli_moment_count = ${count}u;\n")
  jelli_activities_favorites("${data}" ${count} favorites)
  string(APPEND body "${favorites}")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_activities_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
