function(jelli_collection_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/pets.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON root_fields LENGTH "${data}")
  if(NOT root_fields EQUAL 4)
    message(FATAL_ERROR "Unknown or missing catalog fields")
  endif()
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" entries)
  string(JSON growth GET "${data}" evolution_sets 0 growth_ticks)
  string(JSON sets LENGTH "${data}" evolution_sets)
  string(JSON forms LENGTH "${data}" forms)
  string(JSON set_id GET "${data}" evolution_sets 0 id)
  string(JSON start GET "${data}" evolution_sets 0 forms 0)
  string(JSON end GET "${data}" evolution_sets 0 forms 1)
  string(JSON form_count LENGTH "${data}" evolution_sets 0 forms)
  if(NOT sets EQUAL 1 OR NOT set_id EQUAL 1 OR NOT forms EQUAL 2 OR NOT form_count EQUAL 2 OR NOT start EQUAL 0 OR NOT end EQUAL 1)
    message(FATAL_ERROR "This slice supports the Mint-to-Lilac evolution set")
  endif()
  if(NOT version EQUAL 1 OR NOT count EQUAL 9 OR NOT growth MATCHES "^[0-9]+$" OR growth LESS 1 OR growth GREATER 864000)
    message(FATAL_ERROR "Invalid bounded pet catalog")
  endif()
  set(body "#include \"jelli/collection.h\"\nconst uint32_t jelli_collection_growth_ticks = ${growth}u;\nconst JelliCollectionEntry jelli_collection_entries[9] = {\n")
  foreach(i RANGE 0 8)
    foreach(field id name unlock_prize hint evolution_set)
      string(JSON ${field} GET "${data}" entries ${i} ${field})
    endforeach()
    math(EXPR expected "${i} + 1")
    string(LENGTH "${name}" name_length)
    string(LENGTH "${hint}" hint_length)
    if(NOT id MATCHES "^[0-9]+$" OR NOT evolution_set MATCHES "^[0-9]+$" OR NOT evolution_set EQUAL set_id OR NOT id EQUAL expected OR NOT unlock_prize MATCHES "^[0-9]+$" OR unlock_prize GREATER 9 OR NOT name MATCHES "^[A-Z0-9 ]+$" OR name_length GREATER 16 OR NOT hint MATCHES "^[A-Z0-9 ]+$" OR hint_length GREATER 24)
      message(FATAL_ERROR "Invalid pet entry ${i}")
    endif()
    if(i LESS 2 AND NOT unlock_prize EQUAL 0)
      message(FATAL_ERROR "The two legacy companions must remain starters")
    endif()
    string(APPEND body "    {${id}u, ${unlock_prize}u, ${evolution_set}u, \"${name}\", \"${hint}\"},\n")
  endforeach()
  string(APPEND body "};\n")
  string(APPEND body "const JelliCollectionForm jelli_collection_forms[2] = {\n")
  foreach(i RANGE 0 1)
    foreach(field id name portrait)
      string(JSON ${field} GET "${data}" forms ${i} ${field})
    endforeach()
    string(LENGTH "${name}" name_length)
    math(EXPR expected_portrait "1001 + ${i} * 6")
    if(NOT id MATCHES "^[0-9]+$" OR NOT portrait MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT portrait EQUAL expected_portrait OR NOT name MATCHES "^[A-Z0-9 ]+$" OR name_length GREATER 16)
      message(FATAL_ERROR "Unsupported form profile ${i}")
    endif()
    string(APPEND body "    {${portrait}u, \"${name}\"},\n")
  endforeach()
  string(APPEND body "};\n")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_collection_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
