function(jelli_exercise_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/exercise.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  set(values "")
  foreach(field duration_ticks fullness_cost hydration_cost energy_cost amusement_gain)
    string(JSON value GET "${data}" ${field})
    if(NOT value MATCHES "^[0-9]+$" OR value LESS 1 OR value GREATER 1000)
      message(FATAL_ERROR "Exercise ${field} must be 1..1000")
    endif()
    string(APPEND values "${value}u,")
  endforeach()
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_exercise_data.c")
  file(WRITE "${path}" "#include \"jelli/nutrition.h\"\nconst JelliExercise jelli_exercise = {${values}};\n")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
