# Stable saved location IDs, shared by behavior, activity, travel and rendering.
function(jelli_location_names root output)
  set(source "${root}/content/locations.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" locations)
  if(NOT version EQUAL 1 OR count LESS 2 OR count GREATER 8)
    message(FATAL_ERROR "Location catalog needs version 1 and 2..8 places")
  endif()
  set(names "")
  set(labels "")
  math(EXPR last "${count} - 1")
  foreach(i RANGE 0 ${last})
    string(JSON id GET "${data}" locations ${i} id)
    string(JSON key GET "${data}" locations ${i} key)
    string(JSON name GET "${data}" locations ${i} name)
    string(LENGTH "${name}" length)
    if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT key MATCHES "^[a-z][a-z_]*$" OR
       key IN_LIST names OR name IN_LIST labels OR NOT name MATCHES "^[A-Z0-9 ]+$" OR length GREATER 12)
      message(FATAL_ERROR "Location ${i} needs its stable sequential ID, unique key and short name")
    endif()
    if((i EQUAL 0 AND NOT key STREQUAL "home") OR (i EQUAL 1 AND NOT key STREQUAL "garden"))
      message(FATAL_ERROR "Home/Garden must retain stable IDs 0/1")
    endif()
    list(APPEND names "${key}")
    list(APPEND labels "${name}")
  endforeach()
  set(${output} "${names}" PARENT_SCOPE)
endfunction()

function(jelli_locations_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  jelli_location_names("${root}" names)
  set(manifest "${root}/assets/slice/assets.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${manifest}")
  file(READ "${root}/content/locations.json" data)
  file(READ "${manifest}" assets)
  string(JSON asset_count LENGTH "${assets}" assets)
  math(EXPR last_asset "${asset_count} - 1")
  set(backgrounds "")
  foreach(i RANGE 0 ${last_asset})
    string(JSON kind GET "${assets}" assets ${i} kind)
    if(kind STREQUAL "backgrounds")
      string(JSON id GET "${assets}" assets ${i} id)
      list(APPEND backgrounds "${id}")
    endif()
  endforeach()
  list(LENGTH names count)
  math(EXPR last "${count} - 1")
  set(body "#include \"jelli/locations.h\"\nconst JelliLocation jelli_locations[] = {\n")
  foreach(i RANGE 0 ${last})
    string(JSON name GET "${data}" locations ${i} name)
    string(JSON background GET "${data}" locations ${i} background)
    string(JSON outdoors GET "${data}" locations ${i} outdoors)
    string(JSON outdoors_type TYPE "${data}" locations ${i} outdoors)
    if(NOT background IN_LIST backgrounds OR NOT outdoors_type STREQUAL "BOOLEAN")
      message(FATAL_ERROR "Location ${name} needs an existing background asset and boolean outdoors")
    endif()
    if(outdoors)
      set(outdoors "true")
    else()
      set(outdoors "false")
    endif()
    string(APPEND body "    {\"${name}\", \"@ ${name}\", ${background}u, ${outdoors}},\n")
  endforeach()
  string(APPEND body "};\nconst unsigned jelli_location_count = ${count}u;\n")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_locations_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
