function(jelli_wake_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  set(source "${root}/content/wake.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}")
  file(READ "${source}" data)
  foreach(field nap_ticks sleep_ticks bond_gain)
    string(JSON ${field} GET "${data}" ${field})
    if(NOT ${field} MATCHES "^[0-9]+$" OR ${field} LESS 1)
      message(FATAL_ERROR "Invalid wake ${field}")
    endif()
  endforeach()
  if(nap_ticks GREATER sleep_ticks OR sleep_ticks GREATER 864000 OR bond_gain GREATER 1000)
    message(FATAL_ERROR "Wake thresholds or bonding gain exceed bounded limits")
  endif()
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_wake_data.c")
  file(WRITE "${path}" "#include \"jelli/wake.h\"\nconst JelliWakeRules jelli_wake_rules = {${nap_ticks}u, ${sleep_ticks}u, ${bond_gain}u};\n")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
