include("${CMAKE_CURRENT_LIST_DIR}/JelliLocations.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/JelliActivityCosts.cmake")
# Moments (the Activities ring) from content/activities.json; see RFC-005.
function(jelli_activities_moment data i body_variable)
  foreach(field id name kind suggest_hour icon prop duration_s start_minute end_minute random_weight requires animation)
    string(JSON ${field} GET "${data}" moments ${i} ${field})
  endforeach()
  string(LENGTH "${name}" name_length)
  if(NOT id MATCHES "^[0-9]+$" OR NOT id EQUAL i OR NOT name MATCHES "^[A-Z0-9 ]+$" OR name_length GREATER 12)
    message(FATAL_ERROR "Invalid moment ${i}: id must equal its position; name is A-Z/0-9, at most 12")
  endif()
  if(NOT kind MATCHES "^(feed|play)$" )
    message(FATAL_ERROR "Invalid moment ${name}: kind feed|play")
  endif()
  if(NOT suggest_hour MATCHES "^-?[0-9]+$" OR suggest_hour LESS -1 OR suggest_hour GREATER 23)
    message(FATAL_ERROR "Invalid moment ${name}: suggest_hour is -1 (never) or 0..23")
  endif()
  if(NOT icon MATCHES "^[0-9]+$" OR icon LESS 1 OR NOT prop MATCHES "^[0-9]+$")
    message(FATAL_ERROR "Invalid moment ${name}: icon is an asset ID; prop is an asset ID or 0")
  endif()
  foreach(effect gains costs)
    set(${effect} "")
    string(JSON effect_text GET "${data}" moments ${i} ${effect})
    string(JSON effect_type TYPE "${data}" moments ${i} ${effect})
    if(NOT effect_type STREQUAL "OBJECT")
      message(FATAL_ERROR "${effect} must be a meter object")
    endif()
    string(JSON effect_count LENGTH "${data}" moments ${i} ${effect})
    if(effect_count GREATER 0)
      math(EXPR last_effect "${effect_count} - 1")
      foreach(k RANGE 0 ${last_effect})
        string(JSON key MEMBER "${data}" moments ${i} ${effect} ${k})
        if(NOT key MATCHES "^(satiety|energy|hygiene|amusement|social|hydration|bond)$")
          message(FATAL_ERROR "Invalid moment ${name}: unknown meter ${key}")
        endif()
      endforeach()
    endif()
    foreach(need satiety energy hygiene amusement social hydration bond)
      string(JSON value ERROR_VARIABLE missing GET "${data}" moments ${i} ${effect} ${need})
      if(missing)
        set(value 0)
      elseif(NOT value MATCHES "^[0-9]+$" OR value GREATER 1000)
        message(FATAL_ERROR "Invalid moment ${name}: ${need} ${effect} is 0..1000")
      endif()
      string(APPEND ${effect} "${value}u, ")
    endforeach()
  endforeach()
  string(JSON jitter GET "${data}" moments ${i} jitter_pct)
  if(NOT jitter MATCHES "^[0-9]+$" OR jitter GREATER 25)
    message(FATAL_ERROR "Activity reward jitter is 0..25 percent")
  endif()
  string(JSON bonus_count LENGTH "${data}" moments ${i} bonuses)
  if(bonus_count GREATER 8)
    message(FATAL_ERROR "At most 8 pet bonuses per activity")
  endif()
  set(bonuses "{0u, 0u}")
  set(bonus_forms "")
  if(bonus_count GREATER 0)
    set(bonuses "")
    math(EXPR last_bonus "${bonus_count} - 1")
    foreach(b RANGE 0 ${last_bonus})
      string(JSON form GET "${data}" moments ${i} bonuses ${b} form)
      string(JSON percent GET "${data}" moments ${i} bonuses ${b} percent)
      if(NOT form IN_LIST valid_forms OR form IN_LIST bonus_forms OR
         NOT percent MATCHES "^[0-9]+$" OR percent GREATER 100)
        message(FATAL_ERROR "Activity bonuses need unique known forms and 0..100 percent")
      endif()
      list(APPEND bonus_forms "${form}")
      string(APPEND bonuses "{${form}u, ${percent}u}, ")
    endforeach()
  endif()
  foreach(field duration_s start_minute end_minute random_weight)
    if(NOT ${field} MATCHES "^[0-9]+$")
      message(FATAL_ERROR "Invalid moment ${name}: ${field} must be an integer")
    endif()
  endforeach()
  if(duration_s LESS 1 OR duration_s GREATER 3600 OR start_minute GREATER 1439 OR
     end_minute GREATER 1440 OR NOT end_minute GREATER start_minute OR random_weight GREATER 100)
    message(FATAL_ERROR "Invalid moment ${name}: duration 1..3600, window 0..1440, weight 0..100")
  endif()
  if(NOT requires MATCHES "^-?[0-9]+$" OR requires LESS -1 OR NOT requires LESS i)
    message(FATAL_ERROR "Invalid moment ${name}: requires must name an earlier ID, or -1")
  endif()
  set(animations hold sip watch breathe jog cast dream rest think lift sketch dig kick volley swim swing catch mix)
  list(FIND animations "${animation}" animation_index)
  if(animation_index LESS 0)
    message(FATAL_ERROR "Invalid moment ${name}: unknown animation")
  endif()
  string(JSON place_count LENGTH "${data}" moments ${i} locations)
  if(place_count LESS 1 OR place_count GREATER 8)
    message(FATAL_ERROR "Activity ${name} needs 1..8 supported locations")
  endif()
  set(place_mask 0)
  set(used_places "")
  math(EXPR last_place "${place_count} - 1")
  foreach(p RANGE 0 ${last_place})
    string(JSON place GET "${data}" moments ${i} locations ${p})
    list(FIND location_names "${place}" place_id)
    if(place_id LESS 0 OR place IN_LIST used_places)
      message(FATAL_ERROR "Activity ${name}: unknown or duplicate location ${place}")
    endif()
    list(APPEND used_places "${place}")
    math(EXPR place_mask "${place_mask} | (1 << ${place_id})")
  endforeach()
  string(JSON randomize_type TYPE "${data}" moments ${i} randomize_location)
  string(JSON randomize GET "${data}" moments ${i} randomize_location)
  if(NOT randomize_type STREQUAL "BOOLEAN")
    message(FATAL_ERROR "randomize_location must be boolean")
  endif()
  if(randomize)
    set(randomize "true")
  else()
    set(randomize "false")
  endif()
  set(form_mask 0)
  string(JSON forms_count LENGTH "${data}" moments ${i} forms)
  if(forms_count GREATER 0)
    math(EXPR last_form "${forms_count} - 1")
    foreach(f RANGE 0 ${last_form})
      string(JSON form GET "${data}" moments ${i} forms ${f})
      if(NOT form MATCHES "^[0-9]+$" OR form GREATER 31)
        message(FATAL_ERROR "Invalid moment ${name}: forms must be IDs 0..31")
      endif()
      math(EXPR form_mask "${form_mask} | (1 << ${form})")
    endforeach()
  endif()
  foreach(edge start end)
    math(EXPR ${edge}_hour "${${edge}_minute} / 60")
    math(EXPR ${edge}_min "${${edge}_minute} % 60")
    foreach(unit hour min)
      if(${edge}_${unit} LESS 10)
        set(${edge}_${unit} "0${${edge}_${unit}}")
      endif()
    endforeach()
  endforeach()
  set(window_hint "${start_hour}:${start_min} TO ${end_hour}:${end_min}")
  set(prerequisite_hint "")
  if(NOT requires EQUAL -1)
    string(JSON required_name GET "${data}" moments ${requires} name)
    set(prerequisite_hint "${required_name} FIRST")
  endif()
  math(EXPR required "${requires} + 1")
  string(TOUPPER "${kind}" kind)
  if(suggest_hour EQUAL -1)
    set(suggest_hour 255)
  endif()
  set(${body_variable} "    {\"${name}\", \"${window_hint}\", \"${prerequisite_hint}\", JELLI_MOMENT_${kind}, ${place_mask}u, ${randomize}, ${suggest_hour}u, {${gains}}, {${costs}}, ${jitter}u, ${bonus_count}u, {${bonuses}}, ${duration_s}u, ${start_minute}u, ${end_minute}u, ${form_mask}u, ${random_weight}u, ${required}u, ${animation_index}u, ${icon}u, ${prop}u},\n" PARENT_SCOPE)
endfunction()

# Favourite moments: profile = pet ID modulo profile count; each profile names its favourite
# moment per time-of-day window and when its bonus is strongest.
function(jelli_activities_favorites data moment_count out)
  string(JSON bond GET "${data}" favorites bond)
  string(JSON count LENGTH "${data}" favorites profiles)
  if(NOT bond MATCHES "^[0-9]+$" OR bond GREATER 100 OR count LESS 1 OR count GREATER 4)
    message(FATAL_ERROR "favorites needs bond 0..100 and 1..4 profiles")
  endif()
  set(rows "")
  math(EXPR last "${count} - 1")
  foreach(p RANGE 0 ${last})
    string(JSON name GET "${data}" favorites profiles ${p} name)
    string(JSON windows LENGTH "${data}" favorites profiles ${p} windows)
    if(windows LESS 1 OR windows GREATER 4)
      message(FATAL_ERROR "Favourite profile ${name} needs 1..4 windows")
    endif()
    set(cells "")
    set(previous 0)
    math(EXPR last_window "${windows} - 1")
    foreach(w RANGE 0 ${last_window})
      string(JSON until GET "${data}" favorites profiles ${p} windows ${w} until_minute)
      string(JSON moment GET "${data}" favorites profiles ${p} windows ${w} moment)
      if(NOT until MATCHES "^[0-9]+$" OR NOT until GREATER previous OR until GREATER 1440)
        message(FATAL_ERROR "Favourite profile ${name}: until_minute must rise, at most 1440")
      endif()
      set(index -1)
      math(EXPR last_moment "${moment_count} - 1")
      foreach(m RANGE 0 ${last_moment})
        string(JSON candidate GET "${data}" moments ${m} name)
        if(candidate STREQUAL moment)
          set(index ${m})
        endif()
      endforeach()
      if(index LESS 0)
        message(FATAL_ERROR "Favourite profile ${name}: unknown moment '${moment}'")
      endif()
      string(APPEND cells "{${until}u, ${index}u}, ")
      set(previous ${until})
    endforeach()
    if(NOT previous EQUAL 1440)
      message(FATAL_ERROR "Favourite profile ${name}: the last window must end at minute 1440")
    endif()
    foreach(field strong_from_minute strong_until_minute strong_bonus bonus)
      string(JSON ${field} GET "${data}" favorites profiles ${p} ${field})
      if(NOT ${field} MATCHES "^[0-9]+$" OR ${field} GREATER 1440)
        message(FATAL_ERROR "Favourite profile ${name}: ${field} out of range")
      endif()
    endforeach()
    if(strong_until_minute LESS strong_from_minute OR strong_bonus GREATER 200 OR bonus GREATER 200)
      message(FATAL_ERROR "Favourite profile ${name}: strong window or bonuses out of range")
    endif()
    string(APPEND rows "    {{${cells}}, ${windows}u, ${strong_from_minute}u, ${strong_until_minute}u, ${strong_bonus}u, ${bonus}u}, /* ${name} */\n")
  endforeach()
  set(${out} "const JelliFavoriteProfile jelli_favorite_profiles[] = {\n${rows}};\nconst unsigned jelli_favorite_profile_count = ${count}u;\nconst uint16_t jelli_favorite_bond = ${bond}u;\n" PARENT_SCOPE)
endfunction()

function(jelli_activities_data output)
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/.." ABSOLUTE)
  jelli_location_names("${root}" location_names)
  jelli_activity_assets("${root}" asset_ids)
  set(source "${root}/content/activities.json")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}" "${root}/content/pets.json")
  file(READ "${root}/content/pets.json" pets)
  string(JSON form_count LENGTH "${pets}" forms)
  math(EXPR last_form "${form_count} - 1")
  set(valid_forms "")
  foreach(f RANGE 0 ${last_form})
    string(JSON form_id GET "${pets}" forms ${f} id)
    list(APPEND valid_forms "${form_id}")
  endforeach()
  file(READ "${source}" data)
  string(JSON version GET "${data}" version)
  string(JSON count LENGTH "${data}" moments)
  if(NOT version EQUAL 1 OR count LESS 1 OR count GREATER 32)
    message(FATAL_ERROR "Activities need version 1 and 1..32 moments")
  endif()
  math(EXPR last "${count} - 1")
  set(body "#include \"jelli/activities.h\"\nconst JelliMoment jelli_moments[] = {\n")
  set(suggested 0)
  set(names "")
  foreach(i RANGE 0 ${last})
    string(JSON name GET "${data}" moments ${i} name)
    if(name IN_LIST names)
      message(FATAL_ERROR "Duplicate activity name ${name}")
    endif()
    list(APPEND names "${name}")
    string(JSON eligibility_count LENGTH "${data}" moments ${i} forms)
    if(eligibility_count GREATER 0)
      math(EXPR last_eligible "${eligibility_count} - 1")
      foreach(f RANGE 0 ${last_eligible})
        string(JSON form GET "${data}" moments ${i} forms ${f})
        if(NOT form IN_LIST valid_forms)
          message(FATAL_ERROR "Unknown activity form ${form}")
        endif()
      endforeach()
    endif()
    foreach(field icon prop)
      string(JSON asset GET "${data}" moments ${i} ${field})
      if(NOT asset IN_LIST asset_ids AND NOT (field STREQUAL "prop" AND asset EQUAL 0))
        message(FATAL_ERROR "Activity ${name} references missing ${field} asset ${asset}")
      endif()
    endforeach()
    jelli_activities_moment("${data}" ${i} row)
    string(APPEND body "${row}")
    string(JSON hour GET "${data}" moments ${i} suggest_hour)
    if(NOT hour EQUAL -1)
      math(EXPR suggested "${suggested} + 1")
    endif()
  endforeach()
  if(suggested EQUAL 0)
    message(FATAL_ERROR "At least one moment must have a suggest_hour")
  endif()
  string(APPEND body "};\nconst unsigned jelli_moment_count = ${count}u;\n")
  jelli_activities_favorites("${data}" ${count} favorites)
  jelli_activity_pet_costs("${data}" "${valid_forms}" pet_costs)
  string(APPEND body "${favorites}${pet_costs}")
  set(path "${CMAKE_CURRENT_BINARY_DIR}/generated/jelli_activities_data.c")
  file(WRITE "${path}" "${body}")
  set(${output} "${path}" PARENT_SCOPE)
endfunction()
