name: Desktop
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: sudo apt-get update && sudo apt-get install -y ninja-build libsdl2-dev
      - run: make sanitize
      - run: make core-test
